openapi: "3.0.0"

servers:
  - description: Dev
    url: http://localhost:3000/dev
  - description: Sandbox
    url: https://api.sand.gratr.dev
  - description: Staging
    url: https://api.stage.gratr.dev
  - description: Production
    url: https://api.gratr.dev

info:
  description: The API driving GRatr, the best tool to rate, review and select GitHub repositories.
  version: "0.1.0"
  title: GRatr REST API
  contact:
    email: troy.forster@gmail.com
    name: Troy Forster
    url: https://www.tforster.com
  license:
    name: MIT
    url: https://www.gratr.dev/license

tags:
  - name: auth
    description: Authentication and authorisation
  - name: user
    description: Operations for managing users
  - name: subscriptions
    description: Operations specific to teachers for managing subscriptions

paths:
  /auth/tokens:
    post:
      tags:
        - auth
      operationId: tokens
      summary: Sign in with GitHub
      description: |
        Uses GitHub oAuth2 Authorisation Code Grant flow to exchange a GitHub access_token for a GRatr JWT and refresh token.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tokensPostRequest"
      responses:
        "200":
          $ref: "#/components/responses/tokensPost"
        "400":
          $ref: "#/components/responses/Error"

  /auth/refreshtoken:
    post:
      tags:
        - auth
      operationId: refreshtoken
      summary: Refresh token
      description: Refresh token
      responses:
        "204":
          $ref: "#/components/responses/NoContent"
        "400":
          $ref: "#/components/responses/Error"

  /users:
    get:
      operationId: readUsers
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "204":
          $ref: "#/components/responses/NoContent"
        "400":
          $ref: "#/components/responses/Error"

  /{organisation}/{repository}:
    get:
      operationId: readRepository
      summary: Reads the repository
      description: |
        Reads the repository (description)
      parameters:
        - in: path
          name: organisation
          description: The GitHub organisation name
          required: true
          schema:
            $ref: "#/components/schemas/organisationName"
        - in: path
          name: repository
          description: The GitHub repository name
          required: true
          schema:
            $ref: "#/components/schemas/repositoryName"
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: object

components:
  securitySchemes:
    GitHub:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ## Requests

    tokensPostRequest:
      type: object
      properties:
        access_token:
          $ref: "#/components/schemas/gitHubAccessToken"
      additionalProperties: false

    ## Attributes

    gitHubAccessToken:
      description: A token returned from a successful GitHub oAuth2 Authorisation Code Grant flow
      type: string
      example: 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
    jwt:
      description: JSON Web Token
      type: object
    organisationName:
      description: The name of the GitHub organisation
      type: string
      example: tforster
    refreshToken:
      description: A token that can be exchanged for a JWT without logging in a again
      type: string
      example: tbd

    repositoryName:
      description: The name of the GitHub repository
      type: string
      example: joy

  responses:
    tokensPost:
      description: Success. JWT and refreshToken created.
      content:
        application/json:
          schema:
            type: object
            properties:
              jwt:
                $ref: "#/components/schemas/jwt"
              refreshToken:
                $ref: "#/components/schemas/refreshToken"
            additionalProperties: false
    Created:
      description: Createdx
    NoContent:
      description: No content
    UnauthorizedError:
      description: Access token is missing or invalid

    Error:
      description: Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              details:
                type: string
            additionalProperties: false

    NotFoundError:
      description: Resource was not found
    DuplicateError:
      description: Resource already exists
